language: node_js
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: pwd && ls && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
