name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Build Common
        working-directory: ./PandemicCommon
        run: |
          npm ci
          npm run build
      - name: Build Server
        working-directory: ./PandemicServer
        run: |
          npm ci
          npm run check
          npm run test:cloudbuild
          npm run build
      - name: Build Client
        working-directory: ./pandemic-react
        run: |
          npm ci
          npm run check
          npm run test
          npm run build
      - name: Change folder to react
        run: cd ./pandemic-react
      - name: Deploy Client
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
