name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Build Common
        working-directory: ./PandemicCommon
        run: |
          npm ci
          npm run build
      - name: Test Server
        working-directory: ./PandemicServer
        run: |
          npm ci
          npm run check
          npm run test:cloudbuild
      #    npm run build
      - name: Build Client
        working-directory: ./pandemic-react
        run: |
          npm ci
          npm run check
          npm run test:cloudBuild
          npm run build
      - name: Deploy Client
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_PATH: ./pandemic-react
          PROJECT_ID: pandemiconline
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build container image
        run: docker build -t registry.digitalocean.com/personal-projects/pandemic_server:$(echo $GITHUB_SHA | head -c7) .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/personal-projects/pandemic_server:$(echo $GITHUB_SHA | head -c7)
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: deploy
          repository: ${{ secrets.KUBERNETES_REPO_NAME }}
          client-payload: '{"sha": "${ GITHUB_SHA }", "image_name": "pandemic_server"}'
